#!/bin/sh -e

# description
# * compiles the sc source code to c
# dependencies
# * sph-sc
# * clang-format

root="$PWD"
s=source/sc
sm="$s/main"
c="$root/source/c-precompiled"
export SC_LOAD_PATH="$root/$s"

compile_sc() {
  # create the c source code
  cd "$s"
  find -type f -name "*.sc" | sc --stdin-input-paths --parents "$c"
  cd "$root"
  find "$c" -type f -exec ./exe/format-c -i '{}' \;
}

mkdir -p "$c"
compile_sc $@
