#!/bin/sh

optimisation=3
#warnings="-Wunused-label -Wunused-value -Wunused-variable"
gcc_options="$warnings -Wfatal-errors -std=c11 -O$optimisation -I source/c"

compile_sdupes() {
  gcc "source/c-precompiled/main.c" -o temp/sdupes $gcc_options
}

mkdir -p temp &&
compile_sdupes $@ &&
chmod 755 temp/*
