#!/bin/sh

sph_sc_root="$1"
destination="$PWD/src/foreign/sph"
source="$sph_sc_root/src/c-precompiled/sph"

if test -d "$destination"
then
  rm "$destination"/*
else
  mkdir -p "$destination"
fi

cd "$source"
cp hashtable.h array4.h set.h queue.h thread-pool.h thread-pool.c "$destination"
